### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by CaiqueCoelho**
Added documentation for: 
- Retweet a tweet  
- Search for a specific tweet

#3

### CODE REVIEW

**Comment by CaiqueCoelho** [comment]
@richecr I didn't find a method for search for tweets from a specific location and apparently the method for Filter tweets maybe change for another endpoint today the code use `https://stream.twitter.com/1.1`I tried to use the method and nothing was returned, after search in `https://developer.twitter.com/en/docs` I found a new documentation for filter stream `https://api.twitter.com/2/tweets/search/stream` can I create a new issue for the filter method?

**Comment by ghost** [comment]
Hi, @CaiqueCoelho . This is because there is a new version of the Twitter API, before it was in version 1.1, now they are releasing 2.0. From what I followed, they still haven't released all the features for the new API. It would be good to open the issue for this problem of the filter method yes.

One observation is that the method should not return anything, I did some quick tests and it stops at [line 32 of the API.py file](https://github.com/richecr/PyTwitterSDK/blob/3d06139b8ddf5f59e92e7b3aeee2c179466a41a5/py_twitter/utils/API.py#L32), I couldn’t understand what’s causing this problem, I don’t think twitter would take this functionality out of version 1.1.

**Comment by ghost** [comment]
And thanks for the contributions.

**Review by ghost — APPROVED** [review]
Very good.

**Pull request merged**
